// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjTjTMJdSLUzr71Pp11nrUrBJFpewLFMw',
    appId: '1:503590979698:web:4ef0c50b05ba3900601aeb',
    messagingSenderId: '503590979698',
    projectId: 'rlopt-f2860',
    authDomain: 'rlopt-f2860.firebaseapp.com',
    storageBucket: 'rlopt-f2860.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdAsATM4c0_X91ARGj9chZTcsAli3pS6E',
    appId: '1:503590979698:android:6a19881fc94fea57601aeb',
    messagingSenderId: '503590979698',
    projectId: 'rlopt-f2860',
    storageBucket: 'rlopt-f2860.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeFdWzgJ1FDrrjtM6Wb-F2SqjfEhPmCUs',
    appId: '1:503590979698:ios:c210c00bd0209cc9601aeb',
    messagingSenderId: '503590979698',
    projectId: 'rlopt-f2860',
    storageBucket: 'rlopt-f2860.appspot.com',
    androidClientId: '503590979698-ecqij9mpu9n2fbops37p0olothu5ghbb.apps.googleusercontent.com',
    iosClientId: '503590979698-8lao9i8ma3slctl1i8jdclp07989f00o.apps.googleusercontent.com',
    iosBundleId: 'com.example.rloptApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeFdWzgJ1FDrrjtM6Wb-F2SqjfEhPmCUs',
    appId: '1:503590979698:ios:bde14bc9ba960880601aeb',
    messagingSenderId: '503590979698',
    projectId: 'rlopt-f2860',
    storageBucket: 'rlopt-f2860.appspot.com',
    androidClientId: '503590979698-ecqij9mpu9n2fbops37p0olothu5ghbb.apps.googleusercontent.com',
    iosClientId: '503590979698-e5eq1emfp6i90v0eblpak5dlg9bdpo7n.apps.googleusercontent.com',
    iosBundleId: 'com.example.rloptApp.RunnerTests',
  );
}
